from typing import TypedDict, List, Dict, Any, Optional

class FilmStudioState(TypedDict):
    user_prompt: str
    script: Dict[str, Any]           # Generated by Scriptwriter Agent
    storyboard: List[Dict[str, Any]]  # Generated by Storyboard Agent
    audio_tracks: Dict[str, Any]     # Generated by Voice & Sound Agent
    final_video_url: str             # Assembled by Editor Agent
